### PR TITLE
Handle prolongWebView

### PR DESCRIPTION
**Pull request by Fexiven**
According to Telegram (https://core.telegram.org/method/messages.requestWebView) we should prolong it instead of restarting it every 15 minutes

### CODE REVIEW

**Comment by Fexiven** [comment]
I also added some additional patches to the code

**Comment by kpymoumemik** [comment]
help me, what should I do if the console displays “No valid proxy!”

**Comment by kpymoumemik** [comment]
NameError: name 'proxies_data' is not defined. Did you mean: 'proxies_list'?

**Comment by kpymoumemik** [comment]
the console still says "no valid proxy!"

**Comment by Fexiven** [comment]
There's a lot more wrong with this bot, this whole proxy thing is unstable as fuck

And I'm also not 100% sure how it works

**Pull request closed without merging**
